namespace CabRosterApp.Models
{
    public class NodalPoint
    {
        public int Id { get; set; } // This should be auto-generated by the database.
        public string LocationName { get; set; }
    }
}
